site_name: Dynamic Settings
nav:
  - Getting started: index.md
  - How to use: how_to_use.md
  - Tutorials: tutorials.md
  - Client libraries: client_libraries.md
  - Development: development.md


theme:
  name: material
  features:
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  palette:
    accent: teal
    primary: teal

repo_url: https://github.com/MarkAntipin/dynamic-settings